name: Deploy to GitHub Pages

on:
  # Activa el despliegue cada vez que haces push a la rama principal
  push:
    branches: [ main ]
  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Permite que este script haga cambios en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        # with:
          # path: . # Descomenta esto si tu proyecto Astro no está en la raíz del repositorio

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4